draft for listing a duration of analysis
kartoza/geosafe pull request #213
Opened 2017-08-04 06:46 UTC by boney-bun

this commit is unfinished work

push to be reviewed

fix #147

2017-08-04 06:49 UTC, boney-bun commented
@lucernae @ismailsunni i need your opinion on how to calculate the duration.
the proposed start time is on the `process_impact_result` function in `analysis.py`
while, the proposed end time is still on the same function as above, but after the `task_state = 'SUCCESS'`

2017-08-04 07:32 UTC, ismailsunni requested changes
IMHO, it's better to store it as DateTimeField, then do the formating in the jinja (e.g. https://stackoverflow.com/questions/4830535/python-how-do-i-format-a-date-in-jinja2)

By doing this, we can also calculate the elapsed time, or filter based on the date / month, etc.


UPDATE:
@ismailsunni the charField has been changed to DateTimeField.

2017-08-04 07:32 UTC, ismailsunni commented on models.py
> +    start_time = models.CharField(
Why don't you use `DateTimeField`?

2017-08-07 18:16 UTC, boney-bun commented
the code is fully working now. below is a sample snapshot:
One thing that puzzle me: at which points should i calculate the duration?
i've got 5 hours duration if the calculation starts from `Date Created` until `end_time`.
interestingly, i would get 0 minutes if the calculation starts from `start_time` to `end_time`.

- `Date Created` is obtained when impact layers is created for the first time.
- `start_time` is marked when the analysis is saved.
- `end_time` is marked when the `task_state` is `SUCCESS`

i'm thinking to record the `end_time` in function `run_analysis` on `inasafe.headless.tasks.inasafe_wrapper.py`. 
what do you think @ismailsunni @lucernae ?

![screen shot 2017-08-08 at 1 03 21 am](https://user-images.githubusercontent.com/4602383/29039526-ceeb331e-7bd5-11e7-82bf-a3b30ee65cb1.png)

2017-08-10 12:11 UTC, gubuntu commented
I don't think we need to show start and end time, just duration. And the duration above doesn't match the start and end times shown. 

Otherwise LGTM

2017-08-14 09:53 UTC, boney-bun commented
The `duration` field is added to the successful analyses. 
otherwise,`start time` field is used (at this point, there has no infomation about `end time` yet so we can't have a duration):

![screen shot 2017-08-14 at 4 32 08 pm](https://user-images.githubusercontent.com/4602383/29266555-7336d50c-810f-11e7-86ba-41761e0fb6c7.png)

Later, when the analysis succeed, the `start time` information would change to `duration` field.
![screen shot 2017-08-14 at 4 33 51 pm](https://user-images.githubusercontent.com/4602383/29266649-cf9de6be-810f-11e7-865a-140440276318.png)

**Note:**
Even the seconds is taken into account on the time calculation.
0 minutes on the above image because the elapsed time is less than a minute.
the image below is provided as an illustration that it was not actually *zero minute*:
![screen shot 2017-08-14 at 4 33 31 pm](https://user-images.githubusercontent.com/4602383/29266783-362950d0-8110-11e7-8dcd-3efef342182c.png)

2017-08-14 10:00 UTC, boney-bun commented
i'll close this ticket and will merge to staging soon. 
feel free to reopen again.

2017-08-14 10:01 UTC, merged